<?php

declare(strict_types=1);

/**
 * @file
 * Functions to support theming in the swapaxe theme.
 */

/**
 * Implements hook_preprocess_HOOK() for menu-local-task.html.twig.
 */
function swapaxe_preprocess_menu_local_task(array &$variables): void {
  $variables['url']['title'] = $variables['element']['#link']['title'];
  $variables['url']['link'] = $variables['element']['#link']['url']->getInternalPath();
}

